### ISSUE TITLE
other lib

### ISSUE THREAD

**Issue by Rainer-Lang** [PetarMarijanovic/RxActivityResult#3]
Do you know this lib? https://github.com/VictorAlbertos/RxActivityResult

UPDATE: What are the differences? Pros/cons?

**Comment by PetarMarijanovic** [comment]
I believe that you'll be better off with using Victors library since it is more seasoned :)
This is my take on it. I will try to keep it as simple as possible (and working of course), to learn something along the way and to spread the knowledge :)

**Comment by Rainer-Lang** [comment]
I like your convenience methods. Maybe it's possible for you to contribute to Victors lib with some of your ideas....?

**Comment by PetarMarijanovic** [comment]
I just did :)
https://github.com/VictorAlbertos/RxActivityResult/pull/47

**Comment by AlexTrotsenko** [comment]
@PetarMarijanovic  I can't agree with you, that `VictorAlbertos` lib is better nowdays :)

VictorAlbertos lib "helps" you to perform two things:
 1. Rx api to handle `onActivityResult()`
 2. Update ui of current activity in . subscribe(). when Rx task is done  _by handling state of currently active activity_  .

I believe, that standard `LiveData` does 2nd job better nowdays. Thus I would like to have simple lib, which does only Rx api part, e.g. task 1 in the list above.

I was about actually to create my own lib doing exactly what you lib already does. Likely I found your lib before doing this. I will try to use it and give the feedback. So far I like it exactly because of simplicity and doing only one dedicated task.

Also I like current approach with  ["helper fragment"](https://github.com/PetarMarijanovic/RxActivityResult/blob/2.x/library/src/main/java/com/petarmarijanovic/rxactivityresult/RxActivityResultFragment.java#L20). As for me it is more elegant and safe then approach with ["helper activity"](https://github.com/VictorAlbertos/RxActivityResult/blob/3d1b78fefcbc8be786e88a8159fd664d252cc38c/rx_activity_result/src/main/java/rx_activity_result2/HolderActivity.java) in VictorAlbertos lib.

Btw, I have updated the same app to demonstrate how this lib works nicely with LiveData to acomplish before-mentioned job: https://github.com/PetarMarijanovic/RxActivityResult/pull/8
